import type { ClaudeLayout } from "@/utils/zodSchemas";

export type Template = {
  id: string;
  name: string;
  category: string;
  preview: string;
  format: { width: number; height: number; name: string };
  layout: ClaudeLayout;
};

export const TEMPLATES: Template[] = [
  {
    id: "instagram-gradient-hero",
    name: "Post Instagram Gradient",
    category: "Instagram",
    preview: "bg-gradient-to-br from-orange-500 to-rose-600",
    format: { width: 1080, height: 1080, name: "Instagram carré" },
    layout: {
      layout: "hero",
      background: {
        type: "gradient",
        value: "#7c3aed",
        gradient: { from: "#7c3aed", to: "#db2777", direction: "to bottom right" },
      },
      elements: [
        {
          type: "shape",
          id: "el_bg_circle",
          shapeType: "circle",
          position: { x: 700, y: -100, width: 500, height: 500 },
          style: { fill: "rgba(255,255,255,0.08)", opacity: 1 },
          zIndex: 1,
          locked: false,
          visible: true,
        },
        {
          type: "text",
          id: "el_eyebrow",
          content: "NOUVEAU",
          position: { x: 80, y: 300, width: 920, height: 60 },
          style: {
            fontFamily: "Inter",
            fontSize: 18,
            fontWeight: "600",
            color: "rgba(255,255,255,0.7)",
            textAlign: "center",
            letterSpacing: 6,
          },
          zIndex: 2,
          locked: false,
          visible: true,
        },
        {
          type: "text",
          id: "el_headline",
          content: "Votre Titre Principal",
          position: { x: 60, y: 370, width: 960, height: 200 },
          style: {
            fontFamily: "Playfair Display",
            fontSize: 80,
            fontWeight: "bold",
            color: "#ffffff",
            textAlign: "center",
            lineHeight: 1.1,
          },
          zIndex: 3,
          locked: false,
          visible: true,
        },
        {
          type: "text",
          id: "el_subline",
          content: "Une description courte et percutante qui capte l'attention",
          position: { x: 120, y: 590, width: 840, height: 80 },
          style: {
            fontFamily: "Inter",
            fontSize: 26,
            fontWeight: "300",
            color: "rgba(255,255,255,0.85)",
            textAlign: "center",
          },
          zIndex: 4,
          locked: false,
          visible: true,
        },
        {
          type: "shape",
          id: "el_cta_bg",
          shapeType: "rect",
          position: { x: 340, y: 720, width: 400, height: 64 },
          style: { fill: "#ffffff", rx: 32, opacity: 1 },
          zIndex: 5,
          locked: false,
          visible: true,
        },
        {
          type: "text",
          id: "el_cta",
          content: "Découvrir →",
          position: { x: 340, y: 736, width: 400, height: 32 },
          style: {
            fontFamily: "Inter",
            fontSize: 20,
            fontWeight: "600",
            color: "#7c3aed",
            textAlign: "center",
          },
          zIndex: 6,
          locked: false,
          visible: true,
        },
      ],
      colorPalette: ["#7c3aed", "#db2777", "#ffffff"],
      suggestedAnimations: ["fadeIn", "slideFromBottom"],
      copy: { headline: "Votre Titre Principal", subline: "Description percutante", cta: "Découvrir" },
    },
  },
  {
    id: "linkedin-professional",
    name: "LinkedIn Professionnel",
    category: "LinkedIn",
    preview: "bg-gradient-to-r from-zinc-900 to-red-950",
    format: { width: 1200, height: 627, name: "LinkedIn" },
    layout: {
      layout: "split",
      background: {
        type: "gradient",
        value: "#0f172a",
        gradient: { from: "#0f172a", to: "#1e3a5f", direction: "to right" },
      },
      elements: [
        {
          type: "shape",
          id: "el_accent",
          shapeType: "rect",
          position: { x: 0, y: 0, width: 8, height: 627 },
          style: { fill: "#3b82f6", opacity: 1 },
          zIndex: 1,
          locked: false,
          visible: true,
        },
        {
          type: "text",
          id: "el_tag",
          content: "ARTICLE · TECH",
          position: { x: 80, y: 80, width: 700, height: 40 },
          style: {
            fontFamily: "Inter",
            fontSize: 14,
            fontWeight: "600",
            color: "#3b82f6",
            letterSpacing: 3,
          },
          zIndex: 2,
          locked: false,
          visible: true,
        },
        {
          type: "text",
          id: "el_headline",
          content: "5 Stratégies pour Accélérer votre Croissance en 2025",
          position: { x: 80, y: 140, width: 680, height: 200 },
          style: {
            fontFamily: "Inter",
            fontSize: 46,
            fontWeight: "700",
            color: "#ffffff",
            lineHeight: 1.2,
          },
          zIndex: 3,
          locked: false,
          visible: true,
        },
        {
          type: "text",
          id: "el_author",
          content: "Votre Nom · Expert en Innovation",
          position: { x: 80, y: 500, width: 500, height: 40 },
          style: {
            fontFamily: "Inter",
            fontSize: 18,
            fontWeight: "400",
            color: "rgba(255,255,255,0.6)",
          },
          zIndex: 4,
          locked: false,
          visible: true,
        },
        {
          type: "shape",
          id: "el_decoration",
          shapeType: "circle",
          position: { x: 850, y: 100, width: 300, height: 300 },
          style: { fill: "rgba(59,130,246,0.15)", opacity: 1 },
          zIndex: 2,
          locked: false,
          visible: true,
        },
      ],
      colorPalette: ["#0f172a", "#3b82f6", "#ffffff"],
      suggestedAnimations: ["fadeIn", "slideFromLeft"],
      copy: { headline: "5 Stratégies pour Accélérer votre Croissance", cta: "Lire l'article" },
    },
  },
  {
    id: "instagram-minimal-dark",
    name: "Minimal Sombre",
    category: "Instagram",
    preview: "bg-zinc-950 border border-zinc-800",
    format: { width: 1080, height: 1080, name: "Instagram carré" },
    layout: {
      layout: "centered",
      background: { type: "color", value: "#09090b" },
      elements: [
        {
          type: "shape",
          id: "el_line_top",
          shapeType: "rect",
          position: { x: 440, y: 200, width: 200, height: 2 },
          style: { fill: "#ffffff", opacity: 0.3 },
          zIndex: 1,
          locked: false,
          visible: true,
        },
        {
          type: "text",
          id: "el_quote",
          content: "\"La simplicité est la sophistication suprême.\"",
          position: { x: 80, y: 280, width: 920, height: 320 },
          style: {
            fontFamily: "Playfair Display",
            fontSize: 58,
            fontWeight: "400",
            color: "#ffffff",
            textAlign: "center",
            lineHeight: 1.4,
            italic: true,
          },
          zIndex: 2,
          locked: false,
          visible: true,
        },
        {
          type: "shape",
          id: "el_line_bottom",
          shapeType: "rect",
          position: { x: 440, y: 650, width: 200, height: 2 },
          style: { fill: "#ffffff", opacity: 0.3 },
          zIndex: 1,
          locked: false,
          visible: true,
        },
        {
          type: "text",
          id: "el_author",
          content: "— Léonard de Vinci",
          position: { x: 80, y: 680, width: 920, height: 50 },
          style: {
            fontFamily: "Inter",
            fontSize: 22,
            fontWeight: "300",
            color: "rgba(255,255,255,0.5)",
            textAlign: "center",
            letterSpacing: 2,
          },
          zIndex: 3,
          locked: false,
          visible: true,
        },
        {
          type: "text",
          id: "el_brand",
          content: "@votremarque",
          position: { x: 80, y: 940, width: 920, height: 40 },
          style: {
            fontFamily: "Inter",
            fontSize: 18,
            fontWeight: "500",
            color: "rgba(255,255,255,0.3)",
            textAlign: "center",
          },
          zIndex: 4,
          locked: false,
          visible: true,
        },
      ],
      colorPalette: ["#09090b", "#ffffff", "#71717a"],
      suggestedAnimations: ["fadeIn"],
      copy: { headline: "La simplicité est la sophistication suprême.", subline: "— Léonard de Vinci" },
    },
  },
  {
    id: "promo-flash",
    name: "Promo Flash",
    category: "Publicité",
    preview: "bg-gradient-to-br from-amber-500 to-red-600",
    format: { width: 1080, height: 1080, name: "Instagram carré" },
    layout: {
      layout: "hero",
      background: {
        type: "gradient",
        value: "#f59e0b",
        gradient: { from: "#f59e0b", to: "#dc2626", direction: "to bottom right" },
      },
      elements: [
        {
          type: "shape",
          id: "el_badge",
          shapeType: "circle",
          position: { x: 340, y: 100, width: 400, height: 400 },
          style: { fill: "rgba(0,0,0,0.15)", opacity: 1 },
          zIndex: 1,
          locked: false,
          visible: true,
        },
        {
          type: "text",
          id: "el_off",
          content: "-50%",
          position: { x: 80, y: 160, width: 920, height: 260 },
          style: {
            fontFamily: "Inter",
            fontSize: 180,
            fontWeight: "900",
            color: "#ffffff",
            textAlign: "center",
          },
          zIndex: 2,
          locked: false,
          visible: true,
        },
        {
          type: "text",
          id: "el_headline",
          content: "VENTE FLASH",
          position: { x: 80, y: 430, width: 920, height: 80 },
          style: {
            fontFamily: "Inter",
            fontSize: 54,
            fontWeight: "800",
            color: "#ffffff",
            textAlign: "center",
            letterSpacing: 8,
          },
          zIndex: 3,
          locked: false,
          visible: true,
        },
        {
          type: "text",
          id: "el_duration",
          content: "24H SEULEMENT",
          position: { x: 80, y: 530, width: 920, height: 60 },
          style: {
            fontFamily: "Inter",
            fontSize: 28,
            fontWeight: "600",
            color: "rgba(255,255,255,0.8)",
            textAlign: "center",
            letterSpacing: 4,
          },
          zIndex: 4,
          locked: false,
          visible: true,
        },
        {
          type: "shape",
          id: "el_cta_bg",
          shapeType: "rect",
          position: { x: 240, y: 680, width: 600, height: 80 },
          style: { fill: "#ffffff", rx: 12, opacity: 1 },
          zIndex: 5,
          locked: false,
          visible: true,
        },
        {
          type: "text",
          id: "el_cta",
          content: "J'EN PROFITE →",
          position: { x: 240, y: 702, width: 600, height: 36 },
          style: {
            fontFamily: "Inter",
            fontSize: 22,
            fontWeight: "800",
            color: "#dc2626",
            textAlign: "center",
          },
          zIndex: 6,
          locked: false,
          visible: true,
        },
        {
          type: "text",
          id: "el_code",
          content: "Code : FLASH50",
          position: { x: 80, y: 820, width: 920, height: 40 },
          style: {
            fontFamily: "Inter",
            fontSize: 20,
            fontWeight: "500",
            color: "rgba(255,255,255,0.7)",
            textAlign: "center",
          },
          zIndex: 7,
          locked: false,
          visible: true,
        },
      ],
      colorPalette: ["#f59e0b", "#dc2626", "#ffffff"],
      suggestedAnimations: ["zoomIn", "fadeIn"],
      copy: { headline: "VENTE FLASH -50%", subline: "24H SEULEMENT", cta: "J'EN PROFITE" },
    },
  },
  {
    id: "youtube-thumbnail",
    name: "Miniature YouTube",
    category: "YouTube",
    preview: "bg-gradient-to-r from-zinc-900 to-zinc-800",
    format: { width: 1920, height: 1080, name: "YouTube 16:9" },
    layout: {
      layout: "split",
      background: {
        type: "gradient",
        value: "#111827",
        gradient: { from: "#111827", to: "#1f2937", direction: "to right" },
      },
      elements: [
        {
          type: "shape",
          id: "el_accent_bar",
          shapeType: "rect",
          position: { x: 0, y: 0, width: 1920, height: 8 },
          style: { fill: "#ef4444", opacity: 1 },
          zIndex: 1,
          locked: false,
          visible: true,
        },
        {
          type: "text",
          id: "el_number",
          content: "10",
          position: { x: 80, y: 60, width: 400, height: 500 },
          style: {
            fontFamily: "Inter",
            fontSize: 380,
            fontWeight: "900",
            color: "rgba(239,68,68,0.15)",
            textAlign: "left",
          },
          zIndex: 2,
          locked: false,
          visible: true,
        },
        {
          type: "text",
          id: "el_eyebrow",
          content: "TOP",
          position: { x: 80, y: 120, width: 800, height: 80 },
          style: {
            fontFamily: "Inter",
            fontSize: 36,
            fontWeight: "800",
            color: "#ef4444",
            letterSpacing: 8,
          },
          zIndex: 3,
          locked: false,
          visible: true,
        },
        {
          type: "text",
          id: "el_headline",
          content: "Outils IA\nIncontournables",
          position: { x: 80, y: 220, width: 900, height: 360 },
          style: {
            fontFamily: "Inter",
            fontSize: 120,
            fontWeight: "900",
            color: "#ffffff",
            lineHeight: 1.0,
          },
          zIndex: 4,
          locked: false,
          visible: true,
        },
        {
          type: "text",
          id: "el_sub",
          content: "en 2025",
          position: { x: 80, y: 600, width: 900, height: 100 },
          style: {
            fontFamily: "Inter",
            fontSize: 80,
            fontWeight: "300",
            color: "rgba(255,255,255,0.6)",
          },
          zIndex: 5,
          locked: false,
          visible: true,
        },
        {
          type: "shape",
          id: "el_glow",
          shapeType: "circle",
          position: { x: 1200, y: 100, width: 700, height: 700 },
          style: { fill: "rgba(239,68,68,0.08)", opacity: 1 },
          zIndex: 2,
          locked: false,
          visible: true,
        },
      ],
      colorPalette: ["#111827", "#ef4444", "#ffffff"],
      suggestedAnimations: ["fadeIn", "slideFromLeft"],
      copy: { headline: "Top 10 Outils IA en 2025" },
    },
  },
];
